#spring.application.name=invoice-managementt-api
spring.datasource.url=jdbc:postgresql://localhost:5432/invoice_db
spring.datasource.username=invoice_user
spring.datasource.password=invoice_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
